# This is a basic workflow to help you get started with Actions

name: Variaveis de Ambiente

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Variaveis de Ambiente
        run: echo "Bem vindo ao Deploy, $First_Name!"
        env:
          First_Name: "Murilo Bernardes de Oliveira"
